import os
from github import Github
from dotenv import load_dotenv

load_dotenv()

class GitHubHandler:
    def __init__(self, repo_full_name: str):
        # repo_full_name example: "your-username/your-repo-name"
        token = os.getenv("GITHUB_TOKEN")
        self.g = Github(token)
        self.repo = self.g.get_repo(repo_full_name)

    def get_file_content(self, path: str):
        """Fetches the code from the repo so the bot can see it."""
        content = self.repo.get_contents(path)
        return content.decoded_content.decode(), content.sha

    def create_fix_pr(self, file_path: str, new_code: str, branch_name: str):
        """Commits the new code to a new branch and opens a PR."""
        # 1. Get the main branch SHA
        main_branch = self.repo.get_branch("main")
        
        # 2. Create a new branch
        self.repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha)
        
        # 3. Get existing file to get its SHA
        old_content = self.repo.get_contents(file_path, ref="main")
        
        # 4. Update the file in the new branch
        self.repo.update_file(
            path=file_path,
            message="🤖 Auto-fix: Resolved runtime error",
            content=new_code,
            sha=old_content.sha,
            branch=branch_name
        )
        
        # 5. Create the PR
        pr = self.repo.create_pull(
            title="[Auto-Fix] Fix for Runtime Error",
            body="This PR was automatically generated by the CodeSentinel Bot after verifying the fix locally.",
            head=branch_name,
            base="main"
        )
        return pr.html_url