import os
from github import Github
from dotenv import load_dotenv

load_dotenv()

class GitHubManager:
    def __init__(self, repo_name):
        token = os.getenv("GITHUB_TOKEN")
        self.g = Github(token)
        self.repo = self.g.get_repo(repo_name)

    def get_file_content(self, file_path):
        """Reads a file from the repo to understand code structure."""
        try:
            contents = self.repo.get_contents(file_path)
            return contents.decoded_content.decode()
        except Exception as e:
            return f"Error reading file: {e}"

    def create_pr(self, file_path, new_content, branch_name, pr_title):
        """Creates a new branch, commits the fix, and opens a PR."""
        try:
            # 1. Get main branch reference
            source = self.repo.get_branch("main")
            
            # 2. Create new branch
            self.repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=source.commit.sha)
            
            # 3. Get existing file sha (needed for update)
            contents = self.repo.get_contents(file_path)
            
            # 4. Update file in new branch
            self.repo.update_file(contents.path, "Auto-Fix Bot Commit", new_content, contents.sha, branch=branch_name)
            
            # 5. Create PR
            pr = self.repo.create_pull(title=pr_title, body="Generated by Auto-Fix Bot", head=branch_name, base="main")
            return f"PR Created: {pr.html_url}"
        except Exception as e:
            return f"Failed to create PR: {e}"
